Update .net core mac installer to be totally self-contained
The resultant installer is quite large, but has no external dependencies.

diff --git a/Setup/netcoreapp3.1/macos/buildMacInstaller b/Setup/netcoreapp3.1/macos/buildMacInstaller
--- a/Setup/netcoreapp3.1/macos/buildMacInstaller
+++ b/Setup/netcoreapp3.1/macos/buildMacInstaller
@@ -24,7 +24,7 @@ sed -i -e "s/0\.0\.0\.0/$version/g" "$apsimx/Models/Properties/AssemblyVersion.c
 cp "$apsimx/Models/Properties/AssemblyVersion.cs" "$apsimx/ApsimNG/Properties/"
 
 # Publish the build.
-dotnet publish --nologo -f netcoreapp3.1 -c Release --no-self-contained -r osx-x64 "$apsimx/ApsimX.sln"
+dotnet publish --nologo -f netcoreapp3.1 -c Release -r osx-x64 "$apsimx/ApsimX.sln"
 
 # Now generate the installer.
 
@@ -38,7 +38,7 @@ test -d MacBundle && rm -rf MacBundle
 appdir=MacBundle/APSIM$version.app/Contents
 template="$apsimx/Setup/osx/Template"
 copy() {  rsync -aq --mkpath --exclude='*.db' --exclude='*.db-wal' --exclude='*.db-shm' $@; }
-copy $template/Contents/MacOS/ApsimNG $appdir/MacOS/
+copy "$DIR/launcher.sh" $appdir/MacOS/ApsimNG
 copy $template/Contents/Resources/ApsimNG.icns $appdir/Resources/
 copy "$apsimx/Examples" $appdir/Resources/
 copy "$apsimx/Tests/UnderReview" $appdir/Resources/
@@ -46,6 +46,16 @@ copy "$apsimx/ApsimNG/Resources/world" $appdir/Resources/ApsimNG/Resources/
 copy "$apsimx/bin/Release/netcoreapp3.1/osx-x64/publish/*" $appdir/Resources/bin/
 copy "$apsimx/APSIM.bib" $appdir/Resources/
 copy "$plist" $appdir/
+
+# Extract gtk deps
+if [ -z "$GTK_DEPS" ]; then
+    echo "GTK_DEPS variable is not set. Downloading depdendencies..."
+    GTK_DEPS=$(mktemp XXXXXX.tar.gz)
+    url="https://github.com/hol430/apsim-mac/raw/master/deps.tar.gz"
+    curl -o "$GTK_DEPS" "$url"
+fi
+test -f "$GTK_DEPS" || (echo "File not found: GTK_DEPS ($GTK_DEPS)")
+tar xzf "$GTK_DEPS" -C "$appdir/Resources/"
 
 # Now create the .dmg file.
 if [ $# -ge 2 ]; then
