remove unneeded directory check + add error message to model validation workflow if the git merge step fails

diff --git a/.github/workflows/run-model-validations.yml b/.github/workflows/run-model-validations.yml
--- a/.github/workflows/run-model-validations.yml
+++ b/.github/workflows/run-model-validations.yml
@@ -26,19 +26,19 @@ jobs:
           ref: ${{github.event.pull_request.head.ref}}
           fetch-depth: 0  # Fetch all history for all branches and tags
 
-      - name: Change to repository directory if not already there
-        run: |
-          echo "Current working directory: $(pwd)"
-          if [ "$(pwd)" != "/home/runner/work/ApsimX/ApsimX" ]; then
-            echo "Not in the expected directory. Changing directory..."
-            cd /home/runner/work/ApsimX/ApsimX
-          fi
-
       - name: Merge APSIMInitiative/master into PR branch (ensure PR branch up to date)
+        id: merge_upstream
         run: |
           git remote add upstream https://github.com/APSIMInitiative/ApsimX.git || git remote set-url upstream https://github.com/APSIMInitiative/ApsimX.git
           git fetch upstream master
           git merge --no-ff upstream/master || { echo "Merge conflict detected. Aborting merge and exiting."; git merge --abort; exit 1; }
+        continue-on-error: true  # Fail the job if merge fails
+
+      - name: Merge failure
+        if: steps.merge_upstream.outcome == 'failure'
+        run: |
+          echo "::error::Merge failed as PR branch is either not up to date or another issue has occurred."
+          exit 1
       
       - name: Setup .NET Core
         uses: actions/setup-dotnet@v4
